name: mediapipe_text
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/google/flutter-mediapipe
issue_tracker: https://github.com/google/flutter-mediapipe/issues/
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  logging: ^1.2.0
  mediapipe_core:
    path: ../mediapipe-core
  native_assets_cli: ^0.3.0
  native_toolchain_c: ^0.3.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.8
  ffigen: ^9.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  lints: ^2.0.0
